name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Generate Service Worker Cache
        run: |
          echo "self.addEventListener('install', e => { e.waitUntil(caches.open('app-cache-v1').then(c => c.addAll(['/','/index.html','/manifest.json']))); });" > dist/sw.js
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
    permissions: write-all


